---
title: "data-step1"
author: "ShibeiXu"
date: "2021/11/19"
output:html_document
---

```{r setup, include=FALSE}
#Loading library and theme setting
library(haven)
library(tidyverse)
library(rvest)
library(viridis)
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,fig.width = 8, fig.height = 6,out.width = "90%")
options(ggplot2.continuous.colour = "viridis",ggplot2.continuous.fill = "viridis")
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Load the dataset and check the dataset

```{r}
abuse=read_sas("abuse.sas7bdat")
summary(abuse)
```
## Data wrangling

```{r}
abuse_1=abuse%>%
select(pyear,agegrp,outcome,area,BSAE)%>%
filter(outcome%in% c("COCYR", "IEMMON","MRJMON","SUMMON","INCIDENCE","BNGALC","RISKMJ"))%>%
mutate(outcome=as.factor(outcome),
       pyear=as.factor(pyear),
       agegrp=as.factor(agegrp),
       area=as.factor(area),
       BSAE=as.numeric(BSAE))%>%
pivot_wider(names_from = outcome,values_from = BSAE)%>%
  unnest(cols = everything() )
```

